### PR TITLE
Add team to endowed accounts for testnet

### PR DESCRIPTION
**Pull request by JesseAbram**

### CODE REVIEW

**Comment by ameba23** [comment]
Heres mine: `5CtViLgvdHoLDvdsSsfEPxczsF6D7FtQ59h6B4Gey5EXE47t`

**Comment by rh0delta** [comment]
here's mine: 5Dts39fos5FZzskckjtgbnDPnp9ijvKUDz4C2oS4GRWJiGzZ

**Comment by frankiebee** [comment]
5GKEmNJeUpBzGTaXjsTDCXMPtpbhaHDSF9wezMSCZJfGPkez

**Comment by fjarri** [comment]
5FqDurx4mBKFvywkAWfZWtjziKTChoyUjZ4gRKY9hnWRuFZT

**Comment by JesseAbram** [comment]
times up has to go into next release

**Review by HCastano — APPROVED** [review]

**Pull request merged**
